[package]
name = "agena-cgi"
version = "0.1.0"
authors = ["int 80h <int@80h.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
